### ISSUE TITLE
Issues in writing edited glTF.

### ISSUE THREAD

**Issue by 82siha1mpg** [KhronosGroup/glTF-Validator#130]
Hi, 
I am new to 3D modelling and formats. It will be really helpful to get help on my issue. So here it is:
I have a glb file, I am editing "Original.glb" to delete some of the features from it and write a new glb file, For demonstration I have attached glb files.
Issue:- Some of the edited files are showing errors [accessor_too_long] on bufferView 3, whereas on some files it is working. I have checked newly written binaries several times, which shows i have written correct number of bytes required for this element [in the attached example: 864], whereas on importing this with gltf tool in studio code, it shows the above mentioned error and reduced byte length size for the binary data. 
can u pls help me in knowing what would be the issue ?
**
I am sorry, I forget to mention it earlier. That the problem is solved only if I store bufferview2 of same type as of bufferView3. I stored both in 5123 i.e. UNSIGNED_SHORT, so the model looks fine after editing, but it is on other hand is wasting the memory as bufferview2 is original in 5121 type. 
**

Please feel free to ask any question if i am not able to convey it clearly. 
THanks in advance for help.

[CheckGLB.zip](https://github.com/KhronosGroup/glTF-Validator/files/4049377/CheckGLB.zip)

**Comment by lexaknyazev** [comment]
If you are editing a GLB file directly, keep in mind that JSON and BIN data chunks must be aligned to 4-byte boundaries (by using padding as explained in the [GLB specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#glb-file-format-specification)).

The additional error seen in `deleted_Object_check.glb` is caused by `bufferView[3]` using buffer  range `[11232 .. 11232+864]` (i.e. `[11232 .. 12096]`), while the total declared buffer length is `11664`. [This tutorial chapter](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_005_BuffersBufferViewsAccessors.md) may help with understanding glTF data layouts.

Also, all vertex attributes must be aligned to 4-byte boundaries to conform with GPU reqs. This means that, for instance, one-component unsigned byte vertex data still has to use 4 bytes per vertex instead of 1 (by utilizing `bufferView.byteStride` property). A more detailed explanation of "stride" can be found [here](https://github.com/KhronosGroup/glTF/issues/1198#issuecomment-553615402).
