### ISSUE TITLE
Validator as a nuget package.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF-Validator#134]
Now that there's a gltf-validator available as a command line tool, I've been using it internally, wrapped as a convenient C# library that exposes an API to validate gltf files.

I was thinking in publishing the nuget myself, but given that 99% of the code is the gltf-validator itself, I was thinking that maybe you guys would want to have ownership and control of it.

I would be willing to do a pull request with the library prototype, something like gltf2validator.

**Comment by lexaknyazev** [comment]
Sounds interesting. I'm not very familiar with nuget ecosystem though. AFAIK, Microsoft glTF-SDK is no longer published there, for some reason.

@bghgary 
What do you think?

**Comment by bghgary** [comment]
If it's wrapped in a C# wrapper, it would make a lot of sense to publish it as a NuGet package. Khronos already has a NuGet account that we can use.

**Comment by vpenades** [comment]
So, there's an agreement in a pull request?

**Comment by lexaknyazev** [comment]
I think a `nuget` folder would be a proper location for the C# project and its sources (just like `node` contains pieces for building a package for `npm`).

A few comments about overall integration.
- Precompiled executable should never be checked-in into the source tree because it depends on the used Dart SDK version, CPU architecture, and operating system. Instead, it should be built on demand.
  - This project uses `tool/grind.dat` script to manage such tasks. We should have a new build task that compiles the native exe and then builds the nuget package into `build/nuget`.
- Assuming that there's nothing Windows-specific, C# project should target .NET Standard to be compatible with multiple .NET implementations.

There's no need to worry about this stuff for now. Please feel free to open a PR with some C# sources and we'll start from there.

**Comment by vpenades** [comment]
Well... since I am doing glTF validation in different c# projects, and copy/pasting the wrapping code has become a hassle, and given that the plan of contributing it here was unsuccessful, I decided to create a separate repository so I can maintain and publish a nuget package that wraps gltf-validator.

[.Net wrapper for gltf-validator](https://github.com/vpenades/GltfValidator)

I would have preferred this project to be handled under khronos umbrella, but I really needed this to be pushed ASAP.

So sorry if this has caused any inconvenience.

**Comment by emackey** [comment]
Hey @vpenades I'm glad to see this published!  May we link to your NuGet package in the README here?

**Comment by vpenades** [comment]
@emackey sure, no problem with that.
