### ISSUE TITLE
Multiple Extensions warning

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#146]
With the upcoming PBR Next extensions, multiple extensions on a single material object are expected and encouraged.  The validator should not issue a warning for this finding.

Two exceptions: The `KHR_materials_unlit` extension, and the `KHR_materials_pbrSpecularGlossiness` extension, may not co-exist with any of the upcoming PBR Next extensions.  Ideally, the validator should detect that and report a full error, as the specifications have been updated to exclude those two explicitly.

All of the other planned KHR material extensions may co-exist within a single material.  We could issue a warning if a single material calls for more than some number of textures at once (5 or 6?) as low-end implementations could run out of texture samplers (taking environment and LUT into account).

**Comment by lexaknyazev** [comment]
Fixed in `2.0.0-dev.3.3`.

**Comment by aaronfranke** [comment]
This warning is showing up when `KHR_materials_unlit` is used with `VRMC_materials_mtoon`:

<img width="856" height="269" alt="Image" src="https://github.com/user-attachments/assets/43634ffb-118c-44ec-8541-677235f23e3e" />

The `VRMC_materials_mtoon` extension is designed to be used together with `KHR_materials_unlit`, since the intention is that when `VRMC_materials_mtoon` is not supported, the `KHR_materials_unlit` extension serves as a fallback.
