### ISSUE TITLE
Exception thrown from converted code

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#37]
What's the best way to track down exceptions thrown from compiled Dart?

![validationexception](https://user-images.githubusercontent.com/1235080/32516449-5d733436-c3d1-11e7-8875-c44d52625529.png)

In the above example, I've called `validateBytes` on a model (`glTF/NormalTangentTest.gltf`) that is known to validate correctly on the web-based validator.  This is the `2.0.0-dev.1` npm version.

The variables `a` and `z` are `undefined` above.  `J` is a catalog of minified functions.

**Comment by lexaknyazev** [comment]
Fixed in 2f9b1fd3a2bddab3724f577cefa0865e9c9a78c4.

Since it affects JS integration, I think we should publish `2.0.0-dev.1.1`.

Couple comments on debugging:
- `dart2js` produces deterministic output (minified names stay the same as long as input source code doesn't change).
- Minification could be disabled, also source map could be generated (just comment out corresponding lines in `grind.dart`).

**Comment by emackey** [comment]
Great.  Can/should we have a grind task to produce un-minified or source-mapped output for easy debugging?  We wouldn't publish that but it could be manually copied into a project that was throwing exceptions.

**Comment by emackey** [comment]
Also we should update the README demo code to use the options object.

**Comment by lexaknyazev** [comment]
README demo code is correct. I'll add `npm-debug` task.

**Comment by emackey** [comment]
> README demo code is correct

Totally missed that, sorry!

**Comment by lexaknyazev** [comment]
`npm-debug` task has been added in 7128ee36cc3cc1b3826178efc920089cad8495cf.

**Comment by emackey** [comment]
Awesome, thanks!
