### ISSUE TITLE
Consider making parts of API optional for easier adoption

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#41]
The current usage example:

```js
const fs = require("fs");
const path = require("path");
const validator = require('./index.js');

const filename = __dirname + '/Box.gltf';
const asset = fs.readFileSync(filename);

validator.validateBytes(filename, new Uint8Array(asset), (uri) =>
    new Promise((resolve, reject) => {
        uri = path.resolve(path.dirname(filename), uri);
        console.info("Loading external file: " + uri);
        fs.readFile(uri, (err, data) => {
            if (err) {
                console.error(err.toString());
                reject(err.toString());
                return;
            }
            resolve(data);
        });
    }),
    { 
        maxIssues: 10, // limit max number of output issues to 10
        ignoredIssues: [ 'UNSUPPORTED_EXTENSION' ], // mute UNSUPPORTED_EXTENSION issue
        severityOverrides: { 'ACCESSOR_INDEX_TRIANGLE_DEGENERATE': 0 } // treat degenerate triangles as errors 
    }
).then((result) => {
    // [result] will contain validation report in object form.
    // You can convert it to JSON to see its internal structure. 
    console.log(JSON.stringify(result, null, '  '));
}, (result) => {
    // Promise rejection means that validator was unable 
    // to detect file format (glTF or GLB) or has encountered an internal error. 
    // [result] will contain exception object.
    console.error(result.toString());
});
```

This feels a little verbose, and parts of it (especially the `loadExternalResourceCallback` function) will require some work for web developers to set up (multi-file drag and drop is painful on the web...). Is it still possible for the validator to run without additional resources? Also, is the filename required alongside the asset body? If so, I'd consider making some arguments optional, and simplifying the API as follows:

```js
// Basic validation
validator.validateBytes(asset)
  .then((report) => console.log(report))
  .catch((error) => console.error(error));

// Validate with options
validator.validateBytes(asset, {maxIssues: 10})
  .then((report) => console.log(report))
  .catch((error) => console.error(error));

// Validate with options, including external resources
validator.validateBytes(asset, {
    maxIssues: 10,
    externalResourceCallback: (url) => {
      return new Promise((resolve, reject) => { ... });
    }
  })
  .then((report) => console.log(report))
  .catch((error) => console.error(error));
```

**Comment by lexaknyazev** [comment]
Here's current API behaviour. Maybe it needs more docs rather than modifications.

* First argument (`filename`) is used only for `uri` field in validation report (for the report to be identifiable). We may rename it though.
* Callback function could resolve promise with `null` or reject it. Returning `null` will force validator to omit requested resource, otherwise rejection message will be added to the report.
* `options` object and all its fields are optional.

/cc @emackey

**Comment by emackey** [comment]
I do like @donmccurdy's suggestions here in that they bring this API more in line with standard JavaScript APIs.

We really only have one truly required parameter here, that's the asset itself.  The asset may be a self-contained GLB or glTF-Embedded that needs no external resources, and it may be in-memory with no filename associated with it yet.  So it makes sense that `asset` is the first function parameter, and is required, and everything else (including `filename`) is optional within an `options` object that itself is an optional second parameter to the function.  This kind of change would make the API feel more "polished" to experienced JavaScript developers.

> Callback function could resolve promise with null or reject it. Returning null will force validator to omit requested resource, otherwise rejection message will be added to the report.

If the callback function isn't provided at all, that's an indication that the client app isn't capable of delivering external assets.  I'm not sure the use-case for providing this callback and then returning `null` instead of a promise: The client sometimes can deliver external assets, but in this case no?

Certainly a rejected promise should continue in its current behavior, as it likely means file not found or some other major problem.

**Comment by lexaknyazev** [comment]
Is it common to pass functions enclosed in anonymous objects? If so, we can make these changes.
What should report contain when filename wasn't provided? `"uri": null`?

**Comment by emackey** [comment]
> Is it common to pass functions enclosed in anonymous objects?

Yes.  Here's [one example from Cesium's API](https://cesiumjs.org/Cesium/Build/Documentation/ProviderViewModel.html) where a callback function is supplied to create a base imagery layer at a later time, after the user has selected it from the BaseLayerPicker widget.

> What should the report contain when the filename wasn't provided? `"uri": null`?

Yep.  If the app devs want better data coming out, it won't take them long to figure out what they forgot.

**Comment by lexaknyazev** [comment]
Got it. Any naming preferences for fields in the optional object? E.g.
```js
{
  uri: "model.glb",
  maxIssues: 10,
  ignoredIssues: [ 'UNSUPPORTED_EXTENSION' ],
  severityOverrides: { 'ACCESSOR_INDEX_TRIANGLE_DEGENERATE': 0 },
  getExternalResourceFunction: (uri) => ...
}
```

Should we put three existing validation options into a nested object (something like `config`)?

**Comment by emackey** [comment]
* Let's not prefix it with `get` as it sounds too much like a getter.  Just `externalResourceFunction` or `externalResourceCallback` is fine.

* No nested object please.

* Instead of `uri` can we call it just `name`?  Uri sounds like the validator may try to load from it.  I can see a case for keeping it the same as what's in the output though, so no strong opinion here.

One more question:  Is it worth having `ignoredIssues` be separate from `severityOverrides`?  Seems like we could pick a value, like `-1` to disable an issue.  So for the above:

```
{
  name: "model.glb",
  maxIssues: 10,
  severityOverrides: {
    'UNSUPPORTED_EXTENSION': -1
    'ACCESSOR_INDEX_TRIANGLE_DEGENERATE': 0
  },
  externalResourceFunction: (uri) => ...
}
```

**Comment by lexaknyazev** [comment]
> Let's not prefix it with `get` as it sounds too much like a getter.  Just `externalResourceFunction` or `externalResourceCallback` is fine.

OK.

> No nested object please.

OK.

> Instead of `uri` can we call it just `name`?  Uri sounds like the validator may try to load from it.  I can see a case for keeping it the same as what's in the output though, so no strong opinion here.

I'd prefer that field to be treated like proper URI: filename on web and full `file://` scheme on desktop.

> One more question:  Is it worth having `ignoredIssues` be separate from `severityOverrides`?  Seems like we could pick a value, like `-1` to disable an issue.

Current approach matches internal implementation: ignoring issues isn't related to severity overrides. Also, I can see a case for keeping them separate when the same `code` is present in both collections. E.g., a user might need to temporarily mute something while having a predefined set of overrides.

Validator will check all arguments and reject promise (with descriptive message) in case something is wrong.

**Comment by emackey** [comment]
Sounds good.

**Comment by lexaknyazev** [comment]
@emackey @donmccurdy 
PR #42 contains updated JS API. Please review `README.md` and `index.js` there.

**Comment by lexaknyazev** [comment]
@donmccurdy 
JS API was updated in tagged `2.0.0-dev.1.2` release. Feel free to re-open this issue if needed.

**Comment by donmccurdy** [comment]
Great, thanks! The README changes look good to me, will try them out soon.
