### ISSUE TITLE
Error messages language

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Validator#5]
@pjcozzi @tparisi @javagl @lasalvavida
Please review [possible validation issues](https://github.com/KhronosGroup/glTF-Validator/blob/master/ISSUES.md) language. They're auto-generated from Validator API by [this tool](https://github.com/KhronosGroup/glTF-Validator/blob/master/tool/gen_issues_table.dart).

**Comment by javagl** [comment]
Please consider the following only as a list of first thoughts, random nitpicks and possibly stupid questions. The numbers refer to the **Errors** list: 

4, 14  The message does not contain the valid range. It could be helpful to figure out what's wrong

10, 11, 30: I'd spell it `DATA_URI` instead of `DATAURI`, and `BUFFER_VIEW` respectively (but don't want to argue about that)

22, 23, 24, 31, 38, 39 (maybe others): Some constants are named "postiviely", whereas all the others convey the actual error. However, It can be hard to come up with something better. Something like `ACCESSOR_BYTESTRIDE_TOO_SMALL` may be OKish, but  `ACCESSOR_BYTE_OFFSET_NOT_MULTIPLE_OF_COMPONENT_TYPE` may be a bit too elaborate...

25, 30: Just a remark: I think having looked over the relevant code once, and seen that this does not take the offsets into account

31: The requirement is "zfar must be *greater than* znear", so the constant name and message could reflect this

42,43,44: I'll have to review this, but am not sure where these issues are specified. E.g. https://github.com/KhronosGroup/glTF/tree/master/specification#parameternode only says that the node may not be defined when certain sematics are given (and this is somehow covered by 48.). 


---

Again, do **not** take this too serious: For a more profund review, it may be necessary to read the spec, the given list *and* the validator source code in parallel. I was only interested in this because I started some minimalistic "validator" for JglTF as well. When I have a bit more time than now, I might continue with this, and think that the existing validator then could represent a guideline (i.e. a de facto standard) regarding the validation behavior and messages.

Therefore, a more general question: What is the criterion for the classification as "Error" and "Warning"? E.g. "Error 52" is something that I would rather have considered as a Warning, and "Warning 1" may mess things up so severely that I'd treat it as an error. Are there any guidelines or rules of thumb for this?

**Comment by lexaknyazev** [comment]
Thanks for feedback, @javagl !

> 4, 14  The message does not contain the valid range. It could be helpful to figure out what's wrong

Maybe 15? Those errors are raised when value exceeds min/max. Message could be more precise.

> 10, 11, 30: I'd spell it `DATA_URI` instead of `DATAURI`, and `BUFFER_VIEW` respectively

Makes sense, since consts don't use camel case.

> 22, 23, 24, 31, 38, 39 (maybe others): Some constants are named "postiviely", whereas all the others convey the actual error. However, It can be hard to come up with something better. Something like `ACCESSOR_BYTESTRIDE_TOO_SMALL` may be OKish, but  `ACCESSOR_BYTE_OFFSET_NOT_MULTIPLE_OF_COMPONENT_TYPE` may be a bit too elaborate...

Yep, naming those is the most difficult part. Some help would be appreciated.

> 31: The requirement is "zfar must be *greater than* znear", so the constant name and message could reflect this

I've overlooked that in spec, will fix.

> 42,43,44: I'll have to review this, but am not sure where these issues are specified. E.g. https://github.com/KhronosGroup/glTF/tree/master/specification#parameternode only says that the node may not be defined when certain sematics are given (and this is somehow covered by 48.). 

Those restrictions are defined in [1.0.1](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#parametercount).

> Therefore, a more general question: What is the criterion for the classification as "Error" and "Warning"?

Error is something that can lead to invalid GL operation or null-reference runtime exception.
Warning is something "ignorable" (in used contexts).

> "Error 52" is something that I would rather have considered as a Warning

That issue is raised when `parameter` is referenced neither in `attributes`, nor in `uniforms`. I consider such case an error, because it makes impossible to link external references (from `mesh` or `material`).

> "Warning 1" may mess things up so severely that I'd treat it as an error.

When you have embedded data, you have its actual length. So it overrides JSON-stored value (in current implementation, of course subject to change). Later checks (such as bufferView.byteLength) are made against that actual value.

**Comment by lexaknyazev** [comment]
>> 10, 11, 30: I'd spell it `DATA_URI` instead of `DATAURI`, and `BUFFER_VIEW` respectively

> Makes sense, since consts don't use camel case.

and

>> 31: The requirement is "zfar must be *greater than* znear", so the constant name and message could reflect this

> I've overlooked that in spec, will fix.

Fixed with https://github.com/KhronosGroup/glTF-Validator/commit/5bdc8c056a77ab3c851f0123369e0e92156641d9.

**Comment by pjcozzi** [comment]
> DUPLICATE_ITEMS

Throughout the spec, I believe we call these array elements, not items, despite what JSON Schema calls them.  Should we rename to elements or change the spec language?

> NORMALIZED_FLOAT

Should this stay a warning or be an error?

**Comment by lexaknyazev** [comment]
>> NORMALIZED_FLOAT

> Should this stay a warning or be an error?

ES 2.0.25 is silent on that case, ES 3.0.4 states clear (p. 25):

> The normalized flag is ignored if type is `FIXED`, `FLOAT`, or `HALF_FLOAT`.

WebGL 1.0 implementations also ignore that flag with non-integer types.

**Comment by lexaknyazev** [comment]
>> DUPLICATE_ITEMS

> Throughout the spec, I believe we call these array elements, not items, despite what JSON Schema calls them. Should we rename to elements or change the spec language?

Renamed here, spec has too many "elements" usages.

**Comment by pjcozzi** [comment]
> ES 2.0.25 is silent on that case, ES 3.0.4 states clear (p. 25):
>> The normalized flag is ignored if type is FIXED, FLOAT, or HALF_FLOAT.
> WebGL 1.0 implementations also ignore that flag with non-integer types.

OK.

That's all my comments here.  Really nice job organizing and naming these!

**Comment by lexaknyazev** [comment]
@pjcozzi @emackey @UX3D-nopper @javagl 
Please review [ISSUES.md](https://github.com/KhronosGroup/glTF-Validator/blob/master/ISSUES.md) for 2.0.

**Comment by pjcozzi** [comment]
LGTM @lexaknyazev!

**Comment by lexaknyazev** [comment]
I consider this fixed as of `2.0.0-dev.1.0`.
