### ISSUE TITLE
Drag-and-drop validator hangs on some models

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#60]
I tried testing these two models in http://github.khronos.org/glTF-Validator/, and the validator hangs indefinitely for both in Chrome:

[AdamGltfGlb.zip](https://github.com/KhronosGroup/glTF-Validator/files/1605713/AdamGltfGlb.zip)

[AdamGltf.zip](https://github.com/KhronosGroup/glTF-Validator/files/1605714/AdamGltf.zip)

But both can be validated in https://gltf-viewer.donmccurdy.com/, so either (a) there's something weird about the drag-and-drop logic here, or (b) it's related to validating the `.bin` contents (which my app does not do yet). Note that neither glTF file is fully valid.

**Comment by lexaknyazev** [comment]
Looking into this...

If I drop only JSON file into drag-n-drop validator, it validates, prints report, than hangs a bit to apply syntax highlighting (checked in Chrome 63 and Firefox 57). Could you confirm?

**Comment by lexaknyazev** [comment]
The main issue with these files is that they contain too many validation issues (179515 in GLB version and 101600 in regular glTF). I've made couple fixes in `dev.1.7` branch (online version also updated) so that JSON syntax highlighter is disabled when validation report is too big (about 50M for `Adam.glb`). Also browser's console has now timing info so it could be seen that the browser hangs on page composition rather than on validation.

Feel free to re-open this issue if you think something more could be done here.

**Comment by donmccurdy** [comment]
thanks for looking into it! those fixes sound good. :)
