### ISSUE TITLE
accessor min/max tolerance

### ISSUE THREAD

**Issue by CentaurMare** [KhronosGroup/glTF-Validator#79]
I've had this issue for a while, it is evident in models exported from Ruby. Exporting using C# is a bit more accurate and can match the value expected from the validator, but that option isn't available under Sketchup.

The model comes up with this error in the validator but the model doesn't seem to have any issues in the viewer.

> ACCESSOR_MIN_MISMATCH
> Declared minimum value for this component (0) does not match actual minimum (4.526324040084042e-17).

Question: is it actually an error, and what effect does it have on other importers/viewers?

Attached is my test model, it is a TV with a moving image using STEP animation created from a GIF file.
The actual application is C# to create the screen, but then it incorporates the model exported from Sketchup with my exporter.

[tv.zip](https://github.com/KhronosGroup/glTF-Validator/files/1874168/tv.zip)

**Comment by lexaknyazev** [comment]
The validator expects that numbers stored in JSON match those stored in buffers when they are treated with the same precision (IEEE single-precision for floats). 

In your example, the minimum stored value for the second component is `4.526324040084042e-17`. It can be found at position `76` of buffer `35`. Corresponding bytes are `[103, 189, 80, 36]`.

The following Ruby routine produces expected result:
```
> ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
> irb
irb(main):001:0> [103, 189, 80, 36].pack('C*').unpack('f*')
=> [4.526324040084042e-17]
```

**Comment by CentaurMare** [comment]
Thank you!

**Comment by lexaknyazev** [comment]
> I'm having 200 errors in a file, after which validator stops checking anything else.

It's possible to mute individual error codes or set a different maximum number of reported issues by adjusting `glTF.Validation.ignoredIssues` and `glTF.Validation.maxIssues` settings in VSCode:
**File** -> **Preferences** -> **Settings** -> **glTF configutaion**.

> I.e. text value 0.4 has been converted to 0.4000000059604645 anyway. I think some kind of tolerance here would be nice. There's no way to get exactly matching text vs binary value unless this is an integral type.

Before comparison, text values are being coerced to single-precision floating point form (32-bit). Thus, `0.4` becomes `[0xCD, 0xCC, 0xCC, 0x3E]`. For the bounds check to succeed, these four bytes should match maximum binary-stored value from binary buffer.

In your example, maximum value stored in binary buffer is (based on validation report) `[0xCE, 0xCC, 0xCC, 0x3E]`. The validator prints its decimal character sequence (`0.40000003576278687`) that can be parsed back to the original binary form (according to IEEE-754). However, that doesn't mean that it's the only possible decimal form. E.g., `0.40000004` will also be parsed to the same four bytes.

**Comment by gildor2** [comment]
Thanks for quick response and for VSCode information.

Regarding text vs binary floats, I still think that tolerance is required. My glTF sample built with C++ code, not with Java Script. And I'm putting value 0.4 to time track as "maximum value", and immediately printing it to json using printf. The same float value. And then validator says that these values doesn't match. I do not agree if I'd need to use special C++ code (say, print 12 decimal digits when passing value 0.4) just to make JS Validator happy. It wouldn't be so important if this validator won't be used so often. And even with printing so many digits I can't be sure that some browser won't use different FPU settings, and value will match byte-to-byte. Actually, it is usually an error when code tries to compare 2 floating point values without doing tolerance check - unless these values are actually integers (rational numbers).

Just as example. A week ago I've raised an issue with glTF problems to one of Blender glTF guys. There really was a bug, but first thing I had to do is to prove that glTF Validator errors are actually not errors, but rather FPU precision problems.

**Comment by emackey** [comment]
This seems related to #33 (Formalize expected numerical thresholds).

For bounding volumes, I don't think many rendering engines care about having exactly the same four bytes.  Often the bounds are just there to be able to optimize away offscreen geometry.  Putting `0.4` should be a fine approximation for `0.40000003576278687`, I would expect.

**Comment by lexaknyazev** [comment]
float -> string -> float conversion has nothing to do with JavaScript or environment. IEEE-754 standard (which both glTF and JSON specs explicitly refer to) guarantees successful round-trip when there is enough decimal digits, and it just happens that high-level languages (unlike C `printf`) follow its semantics.

What is the reason to introduce yet another arbitrary threshold parameter instead of following common standard, especially given that there are plenty of existing implementations?

**Comment by gildor2** [comment]
Hi Alexey.

Ok. Could you please advise me then, how should I change code to "follow standard"? As I told you before, I have a kind of this code:

    float val = SomeValue;
    sprintf(buf, "%g", val);

'val' goes to binary data, 'buf' goes to json. Files are ready. And then Validator's JavaScript code converts string back to 'float' (I suppose to 'double', because JS as I know doesn't have 'float') and compares it to float 'val' from binary data. And fails. I don't see any problematic case here. The only thing I can suppose is to pass every float value over string, i.e. do this:

    val = SomeValue;
    sprintf(buf, "%g", val);
    sscanf(buf, "%f", &val); // at this point that'll be SomeValue + EPS

i.e. convert string back to the float in my code, to improve chances that if JS code will use under the hood the same CRT function with the same FPU settings, these values will match.

Thanks,
Konstantin

**Comment by lexaknyazev** [comment]
`sprintf`'s behavior is not fully consistent across different compilers/platforms. That's why JSON serialization libraries usually rely on some variant of Grisu2 to ensure successful round-trip:
- RapidJSON (used by COLLADA2GLTF and Maya2glTF):
https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/internal/dtoa.h
- nlohmann/json (used by FBX2glTF):
https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/output/serializer.hpp#L477

The same applies to parsing numbers from JSON.

**Comment by gildor2** [comment]
I'm not [using any thirdparties to generate json](https://github.com/gildor2/UModel/blob/master/Exporters/ExportGLTF.cpp#L631). It is simple enough to be able to not use RapidJSON, STL etc. However, if I understood you right, the code you mentioned will print something like "0.400000000129873" instead of "0.4". I think this is terrible. In my output, I'm trying to make json as compact as possible (while keeping formatting), however it is already larger than bin file containing a mesh and all animations. Using float-to-string which you mentioned, will make it even larger, for no reason.

Well, I understood your point - you think that this is a problem with my code (with CRT which I use). You're right, CRT authors are wrong. Thank you for your time.
